## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly

branches:
    only:
      - master

after_success:
    - julia -e 'cd(Pkg.dir("ForestBiometrics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
    - julia -e 'cd(Pkg.dir("ForestBiometrics")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("ForestBiometrics")); include(joinpath("docs", "make.jl"))'
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("ForestBiometrics"); Pkg.test("ForestBiometrics"; coverage=true)'
