## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - release
  - nightly

branches:
    only:
      - master

## uncomment the following lines to override the default test script
script:
  - julia -e 'cd(Pkg.dir("ForestBiometrics"))'
  - julia -e 'ENV["PYTHON"] = ""; Pkg.add("PyPlot"); Pkg.build("PyPlot")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ForestBiometrics"); Pkg.test("ForestBiometrics"; coverage=true)'


after_success:
    - julia -e 'cd(Pkg.dir("ForestBiometrics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
    #- julia -e 'cd(Pkg.dir("ForestBiometrics")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("ForestBiometrics", "docs")); include("make.jl")'
    - julia -e 'cd(Pkg.dir("ForestBiometrics")); include(joinpath("docs", "make.jl"))'
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly
  - julia: release

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
