language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.3


script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("ForestBiometrics"; coverage=true)'