name = "ForestBiometrics"
uuid = "e560cb43-7f84-4eb8-aabf-6ae6e7008093"
authors = ["crgxcf <crghilardi@yahoo.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = ">= 1.3"
RecipesBase = ">= 1.0"
IterTools = ">= 1.3"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Plots"]
