site_name:        ForestBiometrics.jl
site_description: Description...
site_author:      Casey Ghilardi

repo_name:        Github
repo_url:         https://github.com/Crghilardi/ForestBiometrics.jl

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
